### ISSUE TITLE
HUBOT works locally, but does not connect to HipChat

### ISSUE THREAD

**Issue by sethburtonhall** [hipchat/hubot-hipchat#110]
I am running both the Mac OSX client and the web client.

Hubot runs locally just fine.

I followed all the README directions, but Hubot is not showing up in my HipChat rooms.

Any help?

heroku log

```
2013-06-15T20:13:07.916124+00:00 app[web.1]: Error: Argument error
2013-06-15T20:13:07.916124+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:147:4)
2013-06-15T20:13:07.916124+00:00 app[web.1]:   at new Connector (/app/node_modules/hubot-hipchat/src/connector.coffee:44:13)
2013-06-15T20:13:07.916124+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:124:8, <js>:144:11)
2013-06-15T20:13:07.916124+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2013-06-15T20:13:07.916124+00:00 app[web.1]:   at Robot.run (/app/node_modules/hubot/src/robot.coffee:345:27)
2013-06-15T20:13:08.519318+00:00 heroku[web.1]: Starting process with command `bin/hubot --adapter hipchat`
2013-06-15T20:13:09.351785+00:00 heroku[web.1]: Process exited with status 1
2013-06-15T20:13:09.399560+00:00 app[web.1]: bin/hubot: 3: npm: not found
2013-06-15T20:13:11.898340+00:00 heroku[web.1]: State changed from starting to up
2013-06-15T20:13:12.481958+00:00 app[web.1]:   at HipChat.run (/app/node_modules/hubot-hipchat/src/hipchat.coffee:71:19)
2013-06-15T20:13:12.481958+00:00 app[web.1]:   at new JID (/app/node_modules/hubot-hipchat/node_modules/node-xmpp/lib/xmpp/jid.js:30:15)
2013-06-15T20:13:12.481958+00:00 app[web.1]:   at new Connector (/app/node_modules/hubot-hipchat/src/connector.coffee:44:13)
2013-06-15T20:13:12.481958+00:00 app[web.1]:   at Robot.run (/app/node_modules/hubot/src/robot.coffee:345:27)
2013-06-15T20:13:12.481958+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:124:8, <js>:144:11)
2013-06-15T20:13:12.481958+00:00 app[web.1]: Error: Argument error
2013-06-15T20:13:12.481958+00:00 app[web.1]:
2013-06-15T20:13:12.481958+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:147:4)
2013-06-15T20:13:12.481958+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2013-06-15T20:13:13.897108+00:00 heroku[web.1]: Process exited with status 1
2013-06-15T20:13:13.912925+00:00 heroku[web.1]: State changed from up to crashed
2013-06-15T20:13:13.913673+00:00 heroku[web.1]: State changed from crashed to starting
2013-06-15T20:13:18.868221+00:00 heroku[web.1]: State changed from starting to up
2013-06-15T20:13:20.290815+00:00 heroku[web.1]: State changed from up to crashed
2013-06-15T20:14:03.902696+00:00 heroku[api]: Add HUBOT_HIPCHAT_TOKEN config by seth@ushahidi.com
2013-06-15T20:14:03.942056+00:00 heroku[api]: Release v25 created by seth@ushahidi.com
2013-06-15T20:14:04.081515+00:00 heroku[web.1]: State changed from crashed to starting
2013-06-15T20:14:06.200664+00:00 heroku[web.1]: Starting process with command `bin/hubot --adapter hipchat`
2013-06-15T20:14:07.125392+00:00 app[web.1]: bin/hubot: 3: npm: not found
2013-06-15T20:14:09.058362+00:00 heroku[web.1]: State changed from starting to up
2013-06-15T20:14:09.275383+00:00 app[web.1]: Error: Argument error
2013-06-15T20:14:09.275383+00:00 app[web.1]:   at new JID (/app/node_modules/hubot-hipchat/node_modules/node-xmpp/lib/xmpp/jid.js:30:15)
2013-06-15T20:14:09.275383+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2013-06-15T20:14:09.275383+00:00 app[web.1]:
2013-06-15T20:14:09.275383+00:00 app[web.1]:   at new Connector (/app/node_modules/hubot-hipchat/src/connector.coffee:44:13)
2013-06-15T20:14:09.275383+00:00 app[web.1]:   at HipChat.run (/app/node_modules/hubot-hipchat/src/hipchat.coffee:71:19)
2013-06-15T20:14:09.275383+00:00 app[web.1]:   at Robot.run (/app/node_modules/hubot/src/robot.coffee:345:27)
2013-06-15T20:14:09.275383+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:124:8, <js>:144:11)
2013-06-15T20:14:09.275383+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:147:4)
2013-06-15T20:14:10.557014+00:00 heroku[web.1]: Process exited with status 1
2013-06-15T20:14:10.571709+00:00 heroku[web.1]: State changed from up to crashed
2013-06-15T20:14:58.762104+00:00 heroku[api]: Add HUBOT_HIPCHAT_NAME config by seth@ushahidi.com
2013-06-15T20:14:58.803894+00:00 heroku[api]: Release v26 created by seth@ushahidi.com
2013-06-15T20:14:58.915433+00:00 heroku[web.1]: State changed from crashed to starting
2013-06-15T20:15:00.434034+00:00 heroku[web.1]: Starting process with command `bin/hubot --adapter hipchat`
2013-06-15T20:15:01.155354+00:00 app[web.1]: bin/hubot: 3: npm: not found
2013-06-15T20:15:01.866849+00:00 heroku[web.1]: State changed from starting to up
2013-06-15T20:15:02.219974+00:00 app[web.1]:   at new Connector (/app/node_modules/hubot-hipchat/src/connector.coffee:44:13)
2013-06-15T20:15:02.219974+00:00 app[web.1]:   at new JID (/app/node_modules/hubot-hipchat/node_modules/node-xmpp/lib/xmpp/jid.js:30:15)
2013-06-15T20:15:02.219974+00:00 app[web.1]:   at HipChat.run (/app/node_modules/hubot-hipchat/src/hipchat.coffee:71:19)
2013-06-15T20:15:02.219974+00:00 app[web.1]: Error: Argument error
2013-06-15T20:15:02.219974+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2013-06-15T20:15:02.219974+00:00 app[web.1]:
2013-06-15T20:15:02.219974+00:00 app[web.1]:   at Robot.run (/app/node_modules/hubot/src/robot.coffee:345:27)
2013-06-15T20:15:02.219974+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:147:4)
2013-06-15T20:15:02.219974+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:124:8, <js>:144:11)
2013-06-15T20:15:03.353373+00:00 heroku[web.1]: State changed from up to crashed
2013-06-15T20:15:03.337173+00:00 heroku[web.1]: Process exited with status 1
2013-06-15T20:15:19.244179+00:00 heroku[web.1]: State changed from crashed to starting
2013-06-15T20:15:21.356009+00:00 heroku[web.1]: Starting process with command `bin/hubot --adapter hipchat`
2013-06-15T20:15:23.186535+00:00 app[web.1]: bin/hubot: 3: npm: not found
2013-06-15T20:15:25.349792+00:00 heroku[api]: Scale to web=1 by seth@ushahidi.com
2013-06-15T20:15:26.851020+00:00 heroku[web.1]: State changed from starting to up
2013-06-15T20:15:28.094879+00:00 app[web.1]: Error: Argument error
2013-06-15T20:15:28.094879+00:00 app[web.1]:   at new Connector (/app/node_modules/hubot-hipchat/src/connector.coffee:44:13)
2013-06-15T20:15:28.094879+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2013-06-15T20:15:28.094879+00:00 app[web.1]:   at HipChat.run (/app/node_modules/hubot-hipchat/src/hipchat.coffee:71:19)
2013-06-15T20:15:28.094879+00:00 app[web.1]:   at new JID (/app/node_modules/hubot-hipchat/node_modules/node-xmpp/lib/xmpp/jid.js:30:15)
2013-06-15T20:15:28.094879+00:00 app[web.1]:
2013-06-15T20:15:28.094879+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:124:8, <js>:144:11)
2013-06-15T20:15:28.094879+00:00 app[web.1]:   at Robot.run (/app/node_modules/hubot/src/robot.coffee:345:27)
2013-06-15T20:15:28.094879+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:147:4)
2013-06-15T20:15:29.985408+00:00 heroku[web.1]: State changed from up to crashed
2013-06-15T20:15:29.971219+00:00 heroku[web.1]: Process exited with status 1
2013-06-15T20:16:42.368434+00:00 heroku[api]: Scale to web=1 by seth@ushahidi.com
2013-06-15T20:17:31.899202+00:00 heroku[api]: Remove HUBOT_HIPCHAT_TOKEN config by seth@ushahidi.com
2013-06-15T20:17:31.935874+00:00 heroku[api]: Release v27 created by seth@ushahidi.com
2013-06-15T20:17:32.073152+00:00 heroku[web.1]: State changed from crashed to starting
2013-06-15T20:17:33.506785+00:00 heroku[web.1]: Starting process with command `bin/hubot --adapter hipchat`
2013-06-15T20:17:34.121252+00:00 app[web.1]: bin/hubot: 3: npm: not found
2013-06-15T20:17:35.316082+00:00 app[web.1]: Error: Argument error
2013-06-15T20:17:35.316082+00:00 app[web.1]:   at HipChat.run (/app/node_modules/hubot-hipchat/src/hipchat.coffee:71:19)
2013-06-15T20:17:35.316082+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:147:4)
2013-06-15T20:17:35.316082+00:00 app[web.1]:   at new JID (/app/node_modules/hubot-hipchat/node_modules/node-xmpp/lib/xmpp/jid.js:30:15)
2013-06-15T20:17:35.316082+00:00 app[web.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:124:8, <js>:144:11)
2013-06-15T20:17:35.316082+00:00 app[web.1]:   at Module._compile (module.js:456:26)
2013-06-15T20:17:35.316082+00:00 app[web.1]:   at new Connector (/app/node_modules/hubot-hipchat/src/connector.coffee:44:13)
2013-06-15T20:17:35.316082+00:00 app[web.1]:
2013-06-15T20:17:35.316082+00:00 app[web.1]:   at Robot.run (/app/node_modules/hubot/src/robot.coffee:345:27)
2013-06-15T20:17:36.664876+00:00 heroku[web.1]: Process exited with status 1
2013-06-15T20:17:36.678676+00:00 heroku[web.1]: State changed from starting to crashed
2013-06-15T20:18:37.270581+00:00 heroku[web.1]: State changed from crashed to starting
2013-06-15T20:18:37.131599+00:00 heroku[api]: Add HUBOT_HIPCHAT_JID config by seth@ushahidi.com
2013-06-15T20:18:37.159272+00:00 heroku[api]: Release v28 created by seth@ushahidi.com
2013-06-15T20:18:39.216249+00:00 heroku[web.1]: Starting process with command `bin/hubot --adapter hipchat`
2013-06-15T20:18:40.108572+00:00 app[web.1]: bin/hubot: 3: npm: not found
2013-06-15T20:18:42.348440+00:00 heroku[web.1]: State changed from starting to up
2013-06-15T20:18:44.741044+00:00 app[web.1]: [Sat Jun 15 2013 20:18:44 GMT+0000 (UTC)] INFO Connecting HipChat adapter...
2013-06-15T20:18:45.668615+00:00 app[web.1]: [Sat Jun 15 2013 20:18:45 GMT+0000 (UTC)] INFO Connected to hipchat.com as @chatterbot
2013-06-15T20:18:58.280062+00:00 app[web.1]: [Sat Jun 15 2013 20:18:58 GMT+0000 (UTC)] INFO Joining 52871_hubot@conf.hipchat.com
2013-06-15T20:18:58.306401+00:00 heroku[api]: Scale to web=1 by seth@ushahidi.com
```

**Comment by sravan-bala** [comment]
Adding ntwitter as a dependency worked. Thanks!!
