### ISSUE TITLE
Cannot install hubot-hipchat due to node-gyp error

### ISSUE THREAD

**Issue by dancrumb** [hipchat/hubot-hipchat#170]
I've followed the directions on the README and stumble at the point where I am directed to

    npm install --save hubot-hipchat

The `http GET`s work fine. Then, I see

```
> node-stringprep@0.1.12 install /projects/hipbot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-component/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.11.0-19-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /projects/hipbot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-component/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
```

I have hubot installed, globally, at 2.6.4. I noticed that the `package.json` file that `hubot --create` generates does *not* lock me to hubot v2.6.4, so I tried with that and got the same result.

I appreciate that the problem may simply be in `node-stringprep`, so perhaps the solution is to update this dependency...

**Comment by rbergman** [comment]
Man updates have been applied that should hopefully render this issue obsolete.
