### ISSUE TITLE
Error when trying to start hubot with hipchat adapter

### ISSUE THREAD

**Issue by MrMMorris** [hipchat/hubot-hipchat#210]
So I was using Lita and it was the easiest thing to install, but then I realized that Hubot has more features (and probably better support).

So I install hubot using generator-hubot and everything seems to go fine. I can run hubot with the shell adapter and it responds appropriately. However, now I am trying to get the hipchat adapter running and it has been a huge headache.

I have no idea if the adapter is installed correctly as the output for npm-gyp is incredibly confusing. I have warnings, ERR!'s, xcode-select errors and no 'success' or 'install complete' to be found:

```
$npm install --save hubot-hipchat

npm WARN package.json hubot-maps@0.0.0 No repository field.
\
> node-stringprep@0.2.3 install /Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/node_stringprep.node
  SOLINK_MODULE(target) Release/node_stringprep.node: Finished

> node-stringprep@0.1.12 install /Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-component/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/node_stringprep/node-stringprep.o
../node-stringprep.cc:2:10: fatal error: 'unicode/unistr.h' file not found
#include <unicode/unistr.h>
         ^
1 error generated.
make: *** [Release/obj.target/node_stringprep/node-stringprep.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-component/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing node-stringprep@0.1.12
npm WARN deprecated native-buffer-browserify@2.0.17: please use  (https://www.npmjs.org/package/buffer) instead. this module was renamed.
 
> node-expat@2.3.2 install /Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-expat
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc:42:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2273:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
../node-expat.cc:150:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2273:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
../node-expat.cc:223:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2273:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
3 warnings generated.
  SOLINK_MODULE(target) Release/node_expat.node
  SOLINK_MODULE(target) Release/node_expat.node: Finished

> node-expat@2.1.4 install /Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-component/node_modules/ltx/node_modules/node-expat
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
  SOLINK_MODULE(target) Release/node_expat.node: Finished

> node-expat@2.1.4 install /Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
  SOLINK_MODULE(target) Release/node_expat.node: Finished

> node-expat@2.1.4 install /Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-server/node_modules/ltx/node_modules/node-expat
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
  SOLINK_MODULE(target) Release/node_expat.node: Finished

> node-expat@2.1.4 install /Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-client/node_modules/ltx/node_modules/node-expat
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2' initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node
  SOLINK_MODULE(target) Release/node_expat.node: Finished
hubot-hipchat@2.6.4 node_modules/hubot-hipchat
├── rsvp@1.2.0
├── underscore@1.4.4
└── node-xmpp@0.12.2 (browser-request@0.3.2, faye-websocket@0.7.3, request@2.47.0, ltx@0.7.0, brfs@0.0.8, browserify@3.19.1, node-expat@2.3.2, node-xmpp-component@0.1.1, node-xmpp-core@0.3.3, node-xmpp-server@0.3.5, node-xmpp-client@0.1.9)
```

I have no idea whether this is the same issue as #199 or not because my install doesn't END in ERR!'s (even though they are everywhere else).

**Anyways**, after this confusing output, I try and start hubot with the hipchat adapter and get this:

```
$ bin/hubot -a hipchat

npm WARN package.json hubot-maps@0.0.0 No repository field.
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules/hubot/node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
Error: Argument error
  at new JID (/Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/jid.js:18:15)
  at new Connector (/Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/src/connector.coffee:64:31, <js>:42:13)
  at HipChat.run (/Users/TRX-Arq/Hubot/node_modules/hubot-hipchat/src/hipchat.coffee:70:5, <js>:89:19)
  at Robot.run (/Users/TRX-Arq/Hubot/node_modules/hubot/src/robot.coffee:437:5, <js>:391:27)
  at Object.<anonymous> (/Users/TRX-Arq/Hubot/node_modules/hubot/bin/hubot:135:8, <js>:146:11)
  at Object.<anonymous> (/Users/TRX-Arq/Hubot/node_modules/hubot/bin/hubot:5:1, <js>:149:4)
  at Module._compile (module.js:456:26)
```

What do you know? more useless output. `Error: Argument error` .... alright....

SO, just like everyone else it seems who is trying to use this adapter, I have come here.

Is there a solution to what I believe is a problem I am experiencing?

Sorry for the rant... I was under the assumption a chat bot would make my life easier :wink:

**Comment by pusherman** [comment]
Sounds like you didn't export the environment variables needed in step 13

HUBOT_HIPCHAT_JID and HUBOT_HIPCHAT_PASSWORD

**Comment by tfhartmann** [comment]
+1

**Comment by rbergman** [comment]
Ignore any warnings generated by npm install -- these are emitted from dependencies involved in building node-xmpp*.  They're annoying, but harmless.

@pusherman is right -- you get that crappy error output when you don't configure the required env vars.  Opened #240 to try to improve the error messages.
