### ISSUE TITLE
Error in using adapter hipchat

### ISSUE THREAD

**Issue by muktaa** [hipchat/hubot-hipchat#264]
Trying to start hubot for hipchat, the following fails: yo hubot --adapter hipchat

Get this error:

npm ERR! node-stringprep@0.7.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.7.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

**Comment by muktaa** [comment]
Upgrading npm solved the issue

**Comment by muktaa** [comment]
I still get this error:

$ yo hubot --adapter hipchat

Error:
npm WARN engine hubot-hipchat@2.12.0-5: wanted: {"node":"~0.12.2"} (current: {"node":"0.10.40","npm":"1.4.28"})
 
> node-stringprep@0.7.3 install /home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

which: no icu-config in (/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-core/node_modules/node-stringprep/node_modules/.bin:/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-core/node_modules/.bin:/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/.bin:/home/ec2-user/whbot/node_modules/.bin:/usr/bin:/home/ec2-user/local/bin:/home/ec2-user/hubot/node-v4.2.2-linux-x64/bin:/home/ec2-user/local/bin:/home/ec2-user/local/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ec2-user/bin)
gyp: Call to 'which icu-config > /dev/null || echo n' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-431.11.2.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
 
> node-stringprep@0.7.3 install /home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

which: no icu-config in (/usr/lib/node_modules/npm/bin/node-gyp-bin:/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep/node_modules/.bin:/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/.bin:/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/.bin:/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/.bin:/home/ec2-user/whbot/node_modules/.bin:/usr/bin:/home/ec2-user/local/bin:/home/ec2-user/hubot/node-v4.2.2-linux-x64/bin:/home/ec2-user/local/bin:/home/ec2-user/local/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ec2-user/bin)
gyp: Call to 'which icu-config > /dev/null || echo n' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-431.11.2.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

> iconv@2.1.11 install /home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
> node-gyp rebuild

make: Entering directory `/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv/build'
  CC(target) Release/obj.target/libiconv/deps/libiconv/lib/iconv.o
  AR(target) Release/obj.target/iconv.a
  COPY Release/iconv.a
  CXX(target) Release/obj.target/iconv/src/binding.o
make: g++: Command not found
make: *** [Release/obj.target/iconv/src/binding.o] Error 127
make: Leaving directory `/home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 2.6.32-431.11.2.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/whbot/node_modules/hubot-hipchat/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! node-stringprep@0.7.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.7.3 install script.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-431.11.2.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "hubot" "hubot-scripts" "hubot-diagnostics" "hubot-help" "hubot-heroku-keepalive" "hubot-google-images" "hubot-google-translate" "hubot-pugme" "hubot-maps" "hubot-redis-brain" "hubot-rules" "hubot-shipit" "hubot-hipchat" "--save"
npm ERR! cwd /home/ec2-user/whbot
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by blacksonic** [comment]
Have u tried upgrading the failing package?

**Comment by GSAgentP** [comment]
@muktaa try updating NodeJS to 0.12.2
