### ISSUE TITLE
Connection went offline and Maximum call stack size exceeded when joining >1000 rooms

### ISSUE THREAD

**Issue by ravikiranj** [hipchat/hubot-hipchat#282]
Hi there,
     I'm seeing the following errors when hubot tries to join >1000 rooms (@All) and I'm not sure how to debug it. I'd appreciate any insight into what's going on. The same setup works if numRooms < 500.

Also, if hubot is the right project for this issue and not hubot-hipchat, I can move it. I created it here since I'm using the hipchat adapter.

```
[Thu Nov 03 2016 11:10:04 GMT-0700 (PDT)] INFO Joining 1_poker@conf.btf.hipchat.com
[Thu Nov 03 2016 11:10:04 GMT-0700 (PDT)] INFO Joining 1_aeolian_charme_hotels@conf.btf.hipchat.com


[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] INFO Connection went offline
...


[Thu Nov 03 2016 11:10:10 GMT-0700 (PDT)] ERROR RangeError: Maximum call stack size exceeded
  at emitNone (events.js:65:18)
  at Client.emit (events.js:166:7)
  at Client.<anonymous> (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/Client.js:157:12)
  at emitNone (events.js:72:20)
  at Connection.emit (events.js:166:7)
  at emitter.end.emitter.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_m
odules/reconnect-core/index.js:108:15)
  at Connection.end.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connect
ion.js:124:5)
  at Client.Session.end (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/session.js:202:21)
  at Connector.module.exports.Connector.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:103:5, <js>:84:19)
  at Connector.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:23:1, <js>:3:61)
  at Connector.onOffline (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:503:3, <js>:455:17)
  at emitNone (events.js:67:13)
  at Client.emit (events.js:166:7)
  at Client.<anonymous> (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/Client.js:157:12)
  at emitNone (events.js:72:20)
  at Connection.emit (events.js:166:7)
  at emitter.end.emitter.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_m
odules/reconnect-core/index.js:108:15)
  at Connection.end.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connect
ion.js:124:5)
  at Client.Session.end (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/session.js:202:21)
  at Connector.module.exports.Connector.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:103:5, <js>:84:19)
  at Connector.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:23:1, <js>:3:61)
  at Connector.onOffline (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:503:3, <js>:455:17)
  at emitNone (events.js:67:13)
  at Client.emit (events.js:166:7)
  at Client.<anonymous> (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/Client.js:157:12)
  at emitNone (events.js:72:20)
  at Connection.emit (events.js:166:7)
  at emitter.end.emitter.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_m
odules/reconnect-core/index.js:108:15)
  at Connection.end.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connect
ion.js:124:5)
```

**Comment by ravikiranj** [comment]
I turned on debug and see below in the log


```
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] INFO Joining 1_blu_hotels@conf.btf.hipchat.com
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG  OUT > <presence to="1_blu_hotels@conf.btf.hipchat.com/HipChat Bot Plugin Tester"><x xmlns="http://jabber.org/protocol/muc"/><history xmlns="http://jabber.org/protocol/muc" maxstanzas="0"/></presence>
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] INFO Joining 1_baja_hotels@conf.btf.hipchat.com
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG  OUT > <presence to="1_baja_hotels@conf.btf.hipchat.com/HipChat Bot Plugin Tester"><x xmlns="http://jabber.org/protocol/muc"/><history xmlns="http://jabber.org/protocol/muc" maxstanzas="0"/></presence>
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all
[Tue Nov 08 2016 11:24:52 GMT-0800 (PST)] DEBUG No listeners executed; falling back to catch-all

...

[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] DEBUG Disconnecting here
[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] INFO Connection went offline

... 

[Tue Nov 08 2016 11:24:58 GMT-0800 (PST)] ERROR RangeError: Maximum call stack size exceeded
  at Client.emit (events.js:117:44)
  at emitNone (events.js:72:20)
  at Connection.emit (events.js:166:7)
  at emitter.end.emitter.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/reconnect-core/index.js:108:15)
  at Connection.end.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:124:5)
  at Client.Session.end (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/session.js:202:21)
  at Connector.module.exports.Connector.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:103:5, <js>:84:19)
  at Connector.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:23:1, <js>:3:61)
  at Connector.onOffline (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:503:3, <js>:455:17)
  at emitNone (events.js:67:13)
  at Client.emit (events.js:166:7)
  at Client.<anonymous> (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/Client.js:157:12)
  at emitNone (events.js:72:20)
  at Connection.emit (events.js:166:7)
  at emitter.end.emitter.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/reconnect-core/index.js:108:15)
  at Connection.end.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:124:5)
  at Client.Session.end (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/session.js:202:21)
  at Connector.module.exports.Connector.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:103:5, <js>:84:19)
  at Connector.disconnect (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:23:1, <js>:3:61)
  at Connector.onOffline (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/src/connector.coffee:503:3, <js>:455:17)
  at emitNone (events.js:67:13)
  at Client.emit (events.js:166:7)
  at Client.<anonymous> (/home/rjanardhana/ta-hubot/node_modules/hubot-hipchat/node_modules/node-xmpp-client/lib/Client.js:157:12)
  at emitNone (events.js:72:20)
  at Connection.emit (events.js:166:7)

```

**Comment by fehwalker** [comment]
We're seeing the same with ~1100 rooms -- I suspect it may be related to rate limiting (https://developer.atlassian.com/hipchat/guide/hipchat-rest-api/api-rate-limits)

**Comment by jbrodley** [comment]
I am seeing the same issue on the latest version of hipchat server.

**Comment by jbrodley** [comment]
I ended up opening a ticket with Hipchat support. They were able to look at the logs and realize my issue is that in 2.0.7 and newer server versions XMPP clients are disabled by default. As the Hipchat connector uses the Node JS XMPP Client this is why it started failing after we upgraded.  I was able to enable XMPP protocol by SSH into the server and running "hipchat network --enable-xmpp-ports".  Doesn't resolve the reconnect issue and API limit problem mentioned above, but at least solves my initial problem.

**Comment by ravikiranj** [comment]
@jbrodley Thank you very much for getting to the bottom of this. Yes, we are on custom hosted hipchat server of 2.0.7+.
