### ISSUE TITLE
Unable to connect to Hipchat

### ISSUE THREAD

**Issue by VijiGithub** [hipchat/hubot-hipchat#288]
I am using a ubuntu machine hubot and my hipchat is installed in another server..I have started hubot adapter.I receive the following error
devuser@177:~/myhubot$ bin/hubot --name CRIS --adapter hipchat
[Thu Mar 09 2017 02:29:54 GMT-0800 (PST)] ERROR Error: listen EADDRINUSE 0.0.0.0:8080
  at Object.exports._errnoException (util.js:907:11)
  at exports._exceptionWithHostPort (util.js:930:20)
  at Server._listen2 (net.js:1250:14)
  at listen (net.js:1286:10)
  at net.js:1395:9
  at nextTickCallbackWith3Args (node.js:522:9)
  at process._tickCallback (node.js:428:17)

CRIS> [Thu Mar 09 2017 02:29:54 GMT-0800 (PST)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.

Your hubot-scripts.json is empty, so you just need to remove it.
[Thu Mar 09 2017 02:29:54 GMT-0800 (PST)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web-url | cut -d= -f2)`
[Thu Mar 09 2017 02:29:55 GMT-0800 (PST)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Thu Mar 09 2017 02:29:55 GMT-0800 (PST)] INFO hubot-redis-brain: Initializing new data for hubot brain

I am able to do the following :
CRIS> CRIS PING
CRIS> PONG

But in hipchat CRIS user is offline.

**Comment by anthillmob** [comment]
you have something else running on port 8080 so hubot can't start

```$ sudo lsof -i :8080```

**Comment by VijiGithub** [comment]
Thanks Anthillmob,

How to make my hubot run on other port???
Also , ishipchat JID and password enough to connect to Hipchat becuase we havent stored the username or url of hipchat anywhere.
